import type {
  AIStudyTool,
  ApartmentReview,
  CampusEvent,
  CampusJob,
  Listing,
  LostFoundItem,
  MessagePreview,
  Review,
  RoommateProfile,
  HousingPost,
  SellerProfile,
  SellerReview,
  StudentDiscount,
  Tutor,
  User,
} from "./types";

export const currentUser: User = {
  id: "user-1",
  name: "Alex Rivera",
  username: "@alexrivera",
  avatar: "AR",
  major: "Computer Science",
  year: "Junior",
  verified: true,
  trustScore: 92,
  joinedAt: "2024-08-15",
  bio: "Knights fan, CS major, always down to help with calc homework.",
};

export const users: User[] = [
  currentUser,
  {
    id: "user-2",
    name: "Jordan Kim",
    username: "@jordank",
    avatar: "JK",
    major: "Business",
    year: "Senior",
    verified: true,
    trustScore: 88,
    joinedAt: "2023-01-10",
    bio: "Selling furniture before graduation. Fast responses!",
  },
  {
    id: "user-3",
    name: "Sam Patel",
    username: "@sampatel",
    avatar: "SP",
    major: "Mechanical Engineering",
    year: "Sophomore",
    verified: true,
    trustScore: 95,
    joinedAt: "2024-08-20",
    bio: "Tutor for calc & physics. 4.9★ rating.",
  },
  {
    id: "user-4",
    name: "Mia Chen",
    username: "@miachen",
    avatar: "MC",
    major: "Psychology",
    year: "Junior",
    verified: true,
    trustScore: 90,
    joinedAt: "2024-01-05",
    bio: "Looking for a chill roommate near campus.",
  },
  {
    id: "user-5",
    name: "Chris Williams",
    username: "@chrisw",
    avatar: "CW",
    major: "Film",
    year: "Senior",
    verified: false,
    trustScore: 72,
    joinedAt: "2025-01-12",
    bio: "Freelance videographer on campus.",
  },
  {
    id: "user-6",
    name: "Taylor Brooks",
    username: "@taylorb",
    avatar: "TB",
    major: "Nursing",
    year: "Junior",
    verified: true,
    trustScore: 87,
    joinedAt: "2023-08-28",
    bio: "Lost my ID at the gym — help appreciated!",
  },
];

export const sellerProfiles: SellerProfile[] = [
  {
    id: "seller-1",
    name: "Jordan Kim",
    avatarInitials: "JK",
    email: "jkim@ucf.edu",
    major: "Business",
    year: "Senior",
    campusArea: "Knights Circle",
    rating: 4.8,
    reviewCount: 12,
    trustScore: 88,
    joinedAt: "2023-01-10",
    responseTime: "~1 hour",
    completedSales: 18,
    bio: "Selling furniture before graduation. Fast responses and fair prices!",
    badges: ["Top Seller", "Fast Responder"],
    verified: true,
  },
  {
    id: "seller-2",
    name: "Sam Patel",
    avatarInitials: "SP",
    email: "spatel@knights.ucf.edu",
    major: "Mechanical Engineering",
    year: "Sophomore",
    campusArea: "NorthView",
    rating: 4.9,
    reviewCount: 8,
    trustScore: 95,
    joinedAt: "2024-08-20",
    responseTime: "~30 min",
    completedSales: 11,
    bio: "Engineering student. Selling textbooks and electronics between semesters.",
    badges: ["Verified Student", "Top Rated"],
    verified: true,
  },
  {
    id: "seller-3",
    name: "Mia Chen",
    avatarInitials: "MC",
    email: "mchen@ucf.edu",
    major: "Psychology",
    year: "Junior",
    campusArea: "Main Campus",
    rating: 4.7,
    reviewCount: 6,
    trustScore: 90,
    joinedAt: "2024-01-05",
    responseTime: "~2 hours",
    completedSales: 9,
    bio: "Psych major with great dorm essentials. Meet at Knights Plaza!",
    badges: ["Verified Student"],
    verified: true,
  },
  {
    id: "seller-4",
    name: "Chris Williams",
    avatarInitials: "CW",
    email: "cwilliams@ucf.edu",
    major: "Film",
    year: "Senior",
    campusArea: "Plaza on University",
    rating: 4.5,
    reviewCount: 3,
    trustScore: 72,
    joinedAt: "2025-01-12",
    responseTime: "~4 hours",
    completedSales: 4,
    bio: "Film student selling gaming gear and creative equipment.",
    badges: ["New Seller"],
    verified: false,
  },
  {
    id: "seller-5",
    name: "Alex Rivera",
    avatarInitials: "AR",
    email: "arivera@ucf.edu",
    major: "Computer Science",
    year: "Junior",
    campusArea: "Main Campus",
    rating: 4.9,
    reviewCount: 5,
    trustScore: 92,
    joinedAt: "2024-08-15",
    responseTime: "~45 min",
    completedSales: 7,
    bio: "CS junior. Occasionally list tech and study materials.",
    badges: ["Verified Student", "Trusted Seller"],
    verified: true,
  },
];

export const sellerReviews: SellerReview[] = [
  {
    id: "sr-1",
    sellerId: "seller-1",
    reviewerName: "Taylor Brooks",
    reviewerInitials: "TB",
    rating: 5,
    comment: "Desk was exactly as described. Super easy pickup at Libra!",
    createdAt: "2025-06-15",
    listingTitle: "IKEA Micke Desk",
  },
  {
    id: "sr-2",
    sellerId: "seller-1",
    reviewerName: "Mia Chen",
    reviewerInitials: "MC",
    rating: 5,
    comment: "Jordan responded fast and threw in a desk lamp. Great seller.",
    createdAt: "2025-05-28",
    listingTitle: "Mini Fridge + Microwave Combo",
  },
  {
    id: "sr-3",
    sellerId: "seller-2",
    reviewerName: "Alex Rivera",
    reviewerInitials: "AR",
    rating: 5,
    comment: "Textbook was in great shape. Met at Knights Plaza, smooth deal.",
    createdAt: "2025-06-10",
    listingTitle: "Calculus Early Transcendentals",
  },
  {
    id: "sr-4",
    sellerId: "seller-2",
    reviewerName: "Jordan Kim",
    reviewerInitials: "JK",
    rating: 4,
    comment: "MacBook had minor scratches as noted. Fair price for the model.",
    createdAt: "2025-05-20",
    listingTitle: "MacBook Air M1",
  },
  {
    id: "sr-5",
    sellerId: "seller-3",
    reviewerName: "Sam Patel",
    reviewerInitials: "SP",
    rating: 5,
    comment: "Free boxes saved my move-in. Mia is the best!",
    createdAt: "2025-06-26",
    listingTitle: "Free Moving Boxes",
  },
  {
    id: "sr-6",
    sellerId: "seller-4",
    reviewerName: "Taylor Brooks",
    reviewerInitials: "TB",
    rating: 4,
    comment: "Controller works perfectly. Quick meetup at Lake Claire.",
    createdAt: "2025-06-20",
    listingTitle: "PS5 Controller",
  },
];

export const listings: Listing[] = [
  {
    id: "listing-1",
    title: "IKEA Micke Desk — White, Great Condition",
    description:
      "Barely used desk from IKEA. Perfect for dorm or apartment. Pick up near Libra. Includes original assembly hardware.",
    price: 45,
    category: "furniture",
    condition: "like-new",
    location: "Libra Residence Hall",
    campusArea: "Main Campus",
    sellerId: "seller-1",
    sellerName: "Jordan Kim",
    sellerAvatarInitials: "JK",
    sellerRating: 4.8,
    sellerJoinedAt: "2023-01-10",
    sellerMajor: "Business",
    sellerYear: "Senior",
    images: ["🛋️"],
    tags: ["desk", "dorm", "furniture"],
    postedAt: "2025-06-20",
    updatedAt: "2025-06-20",
    isFeatured: true,
    isNegotiable: true,
    pickupOptions: ["Dorm lobby", "Campus meetup"],
    status: "active",
    views: 142,
    savedCount: 28,
  },
  {
    id: "listing-2",
    title: "Calculus Early Transcendentals 8th Ed",
    description:
      "Used for MAC 2311. Some highlighting, all pages intact. Great for Calc I and II.",
    price: 35,
    category: "textbooks",
    condition: "good",
    location: "Knights Plaza",
    campusArea: "Main Campus",
    sellerId: "seller-2",
    sellerName: "Sam Patel",
    sellerAvatarInitials: "SP",
    sellerRating: 4.9,
    sellerJoinedAt: "2024-08-20",
    sellerMajor: "Mechanical Engineering",
    sellerYear: "Sophomore",
    images: ["📚"],
    tags: ["calculus", "math", "textbook", "MAC2311"],
    postedAt: "2025-06-22",
    updatedAt: "2025-06-22",
    isFeatured: true,
    isNegotiable: false,
    pickupOptions: ["Campus meetup", "In-person pickup"],
    status: "active",
    views: 98,
    savedCount: 41,
  },
  {
    id: "listing-3",
    title: "Electric Scooter — 15mph, Charger Included",
    description:
      "Got a car, don't need it anymore. Works great for campus. Battery holds full charge.",
    price: 180,
    category: "scooters",
    condition: "good",
    location: "NorthView",
    campusArea: "NorthView",
    sellerId: "seller-1",
    sellerName: "Jordan Kim",
    sellerAvatarInitials: "JK",
    sellerRating: 4.8,
    sellerJoinedAt: "2023-01-10",
    sellerMajor: "Business",
    sellerYear: "Senior",
    images: ["🛴"],
    tags: ["scooter", "transport", "commute"],
    postedAt: "2025-06-18",
    updatedAt: "2025-06-19",
    isFeatured: false,
    isNegotiable: true,
    pickupOptions: ["Parking lot handoff", "In-person pickup"],
    status: "active",
    views: 210,
    savedCount: 35,
  },
  {
    id: "listing-4",
    title: "PS5 Controller — Midnight Black",
    description:
      "Lightly used, no drift. Comes with USB-C cable. Perfect for dorm gaming nights.",
    price: 40,
    category: "gaming",
    condition: "like-new",
    location: "Lake Claire",
    campusArea: "Main Campus",
    sellerId: "seller-4",
    sellerName: "Chris Williams",
    sellerAvatarInitials: "CW",
    sellerRating: 4.5,
    sellerJoinedAt: "2025-01-12",
    sellerMajor: "Film",
    sellerYear: "Senior",
    images: ["🎮"],
    tags: ["ps5", "gaming", "controller"],
    postedAt: "2025-06-25",
    updatedAt: "2025-06-25",
    isFeatured: false,
    isNegotiable: false,
    pickupOptions: ["Campus meetup"],
    status: "active",
    views: 67,
    savedCount: 12,
  },
  {
    id: "listing-5",
    title: "Mini Fridge + Microwave Combo",
    description:
      "Perfect dorm setup. Both work perfectly. Must pick up before July 1.",
    price: 75,
    category: "dorm-essentials",
    condition: "good",
    location: "Apollo",
    campusArea: "Main Campus",
    sellerId: "seller-1",
    sellerName: "Jordan Kim",
    sellerAvatarInitials: "JK",
    sellerRating: 4.8,
    sellerJoinedAt: "2023-01-10",
    sellerMajor: "Business",
    sellerYear: "Senior",
    images: ["📦"],
    tags: ["fridge", "microwave", "dorm"],
    postedAt: "2025-06-15",
    updatedAt: "2025-06-15",
    isFeatured: true,
    isNegotiable: true,
    pickupOptions: ["Dorm lobby", "In-person pickup"],
    status: "active",
    views: 156,
    savedCount: 33,
  },
  {
    id: "listing-6",
    title: "MacBook Air M1 — 256GB",
    description:
      "2020 model, great battery life. Minor scratches on bottom. Includes charger.",
    price: 550,
    category: "electronics",
    condition: "good",
    location: "Knights Circle",
    campusArea: "Knights Circle",
    sellerId: "seller-2",
    sellerName: "Sam Patel",
    sellerAvatarInitials: "SP",
    sellerRating: 4.9,
    sellerJoinedAt: "2024-08-20",
    sellerMajor: "Mechanical Engineering",
    sellerYear: "Sophomore",
    images: ["💻"],
    tags: ["macbook", "laptop", "apple"],
    postedAt: "2025-06-10",
    updatedAt: "2025-06-12",
    isFeatured: false,
    isNegotiable: true,
    pickupOptions: ["Campus meetup", "In-person pickup"],
    status: "active",
    views: 312,
    savedCount: 58,
  },
  {
    id: "listing-7",
    title: "Free Moving Boxes (20+)",
    description:
      "Just moved in. Take as many as you need! Various sizes, clean and sturdy.",
    price: 0,
    category: "free-stuff",
    condition: "good",
    location: "The Point at Central",
    campusArea: "The Pointe",
    sellerId: "seller-3",
    sellerName: "Mia Chen",
    sellerAvatarInitials: "MC",
    sellerRating: 4.7,
    sellerJoinedAt: "2024-01-05",
    sellerMajor: "Psychology",
    sellerYear: "Junior",
    images: ["📦"],
    tags: ["free", "moving", "boxes"],
    postedAt: "2025-06-26",
    updatedAt: "2025-06-26",
    isFeatured: false,
    isNegotiable: false,
    pickupOptions: ["In-person pickup"],
    status: "active",
    views: 89,
    savedCount: 22,
  },
  {
    id: "listing-8",
    title: "UCF Football Ticket — vs USF",
    description:
      "Student section, one ticket. Can't make the game. Digital transfer ready.",
    price: 25,
    category: "tickets",
    condition: "new",
    location: "Campus",
    campusArea: "Main Campus",
    sellerId: "seller-4",
    sellerName: "Chris Williams",
    sellerAvatarInitials: "CW",
    sellerRating: 4.5,
    sellerJoinedAt: "2025-01-12",
    sellerMajor: "Film",
    sellerYear: "Senior",
    images: ["🎟️"],
    tags: ["football", "ticket", "ucf"],
    postedAt: "2025-06-24",
    updatedAt: "2025-06-24",
    isFeatured: false,
    isNegotiable: false,
    pickupOptions: ["Campus meetup"],
    status: "active",
    views: 45,
    savedCount: 8,
  },
  {
    id: "listing-9",
    title: "Nike Air Force 1 — Size 10",
    description:
      "Worn a few times, still look fresh. White colorway. Meet at Plaza Tower.",
    price: 60,
    category: "clothes",
    condition: "like-new",
    location: "Plaza Tower",
    campusArea: "Plaza on University",
    sellerId: "seller-1",
    sellerName: "Jordan Kim",
    sellerAvatarInitials: "JK",
    sellerRating: 4.8,
    sellerJoinedAt: "2023-01-10",
    sellerMajor: "Business",
    sellerYear: "Senior",
    images: ["👕"],
    tags: ["shoes", "nike", "sneakers"],
    postedAt: "2025-06-21",
    updatedAt: "2025-06-21",
    isFeatured: false,
    isNegotiable: true,
    pickupOptions: ["Campus meetup", "In-person pickup"],
    status: "active",
    views: 73,
    savedCount: 15,
  },
  {
    id: "listing-10",
    title: "Keurig + K-Cup Organizer",
    description:
      "Coffee setup for your room. Includes 20 k-cups. Works great, just upgraded.",
    price: 30,
    category: "kitchen",
    condition: "good",
    location: "Libra",
    campusArea: "Main Campus",
    sellerId: "seller-3",
    sellerName: "Mia Chen",
    sellerAvatarInitials: "MC",
    sellerRating: 4.7,
    sellerJoinedAt: "2024-01-05",
    sellerMajor: "Psychology",
    sellerYear: "Junior",
    images: ["📦"],
    tags: ["coffee", "keurig", "kitchen"],
    postedAt: "2025-06-19",
    updatedAt: "2025-06-19",
    isFeatured: false,
    isNegotiable: false,
    pickupOptions: ["Dorm lobby"],
    status: "active",
    views: 54,
    savedCount: 11,
  },
  {
    id: "listing-11",
    title: "COP 3503 Data Structures Textbook",
    description:
      "Required for CS2. Clean pages, no water damage. Includes online access code (unused).",
    price: 42,
    category: "textbooks",
    condition: "like-new",
    location: "HPA II",
    campusArea: "Main Campus",
    sellerId: "seller-5",
    sellerName: "Alex Rivera",
    sellerAvatarInitials: "AR",
    sellerRating: 4.9,
    sellerJoinedAt: "2024-08-15",
    sellerMajor: "Computer Science",
    sellerYear: "Junior",
    images: ["📚"],
    tags: ["cs", "textbook", "COP3503"],
    postedAt: "2025-06-27",
    updatedAt: "2025-06-27",
    isFeatured: true,
    isNegotiable: false,
    pickupOptions: ["Campus meetup"],
    status: "active",
    views: 38,
    savedCount: 9,
  },
  {
    id: "listing-12",
    title: "Logitech MX Master 3 Mouse",
    description:
      "Perfect for CS students. Barely used, comes with USB receiver and cable.",
    price: 55,
    category: "electronics",
    condition: "like-new",
    location: "Student Union",
    campusArea: "Main Campus",
    sellerId: "seller-5",
    sellerName: "Alex Rivera",
    sellerAvatarInitials: "AR",
    sellerRating: 4.9,
    sellerJoinedAt: "2024-08-15",
    sellerMajor: "Computer Science",
    sellerYear: "Junior",
    images: ["💻"],
    tags: ["mouse", "logitech", "tech"],
    postedAt: "2025-06-23",
    updatedAt: "2025-06-23",
    isFeatured: false,
    isNegotiable: true,
    pickupOptions: ["Campus meetup", "In-person pickup"],
    status: "active",
    views: 61,
    savedCount: 14,
  },
];

export const housingPosts: HousingPost[] = [
  {
    id: "housing-1",
    title: "1BR Sublease at The Enclave — Furnished",
    description:
      "Fully furnished 1BR available July–December. In-unit washer/dryer, pool, gym.",
    type: "sublease",
    price: 1100,
    location: "The Enclave",
    bedrooms: 1,
    bathrooms: 1,
    availableFrom: "2025-07-01",
    leaseEnd: "2025-12-31",
    amenities: ["Pool", "Gym", "Furnished", "Parking"],
    poster: users[1],
    images: [],
    createdAt: "2025-06-20",
  },
  {
    id: "housing-2",
    title: "Room in 4x4 at NorthView — Private Bath",
    description: "One room available in a clean 4x4. Great roommates, quiet floor.",
    type: "sublease",
    price: 750,
    location: "NorthView",
    bedrooms: 4,
    bathrooms: 4,
    availableFrom: "2025-08-01",
    leaseEnd: "2026-07-31",
    amenities: ["Private Bath", "Shuttle", "Study Rooms"],
    poster: users[3],
    images: [],
    createdAt: "2025-06-18",
  },
  {
    id: "housing-3",
    title: "Lease Transfer — The Point 2x2",
    description: "Need someone to take over my lease. $200 transfer incentive!",
    type: "lease-transfer",
    price: 850,
    location: "The Point at Central",
    bedrooms: 2,
    bathrooms: 2,
    availableFrom: "2025-07-15",
    leaseEnd: "2026-07-31",
    amenities: ["Pool", "Game Room", "Pet Friendly"],
    poster: users[4],
    images: [],
    createdAt: "2025-06-22",
  },
  {
    id: "housing-4",
    title: "Summer Sublease — Plaza Tower Studio",
    description: "Studio unit, walking distance to campus. All utilities included.",
    type: "sublease",
    price: 950,
    location: "Plaza Tower",
    bedrooms: 0,
    bathrooms: 1,
    availableFrom: "2025-06-01",
    leaseEnd: "2025-08-15",
    amenities: ["Utilities Included", "Furnished", "Walk to Campus"],
    poster: users[2],
    images: [],
    createdAt: "2025-06-10",
  },
];

export const roommateProfiles: RoommateProfile[] = [
  {
    id: "roommate-1",
    user: users[3],
    budget: 700,
    moveInDate: "2025-08-01",
    preferredLocation: "Near campus or Alafaya",
    lifestyle: ["Clean", "Early Riser", "Non-smoker", "Quiet"],
    bio: "Psych major looking for a chill roommate. I cook a lot and love plants.",
    compatibility: 94,
  },
  {
    id: "roommate-2",
    user: users[4],
    budget: 650,
    moveInDate: "2025-07-01",
    preferredLocation: "Knights Circle area",
    lifestyle: ["Social", "Night Owl", "Pet Friendly", "Gamer"],
    bio: "Film student, pretty laid back. Down for movie nights and game sessions.",
    compatibility: 78,
  },
  {
    id: "roommate-3",
    user: users[2],
    budget: 800,
    moveInDate: "2025-08-15",
    preferredLocation: "NorthView or The Enclave",
    lifestyle: ["Studious", "Gym", "Non-smoker", "Organized"],
    bio: "Engineering student, usually at the library. Looking for someone similar.",
    compatibility: 88,
  },
];

export const apartmentReviews: ApartmentReview[] = [
  {
    id: "review-apt-1",
    apartmentName: "The Enclave",
    location: "Alafaya Trail",
    rating: 4.2,
    review:
      "Great amenities and location. Management is responsive. Parking can be tight.",
    pros: ["Pool & gym", "Close to campus", "Modern units"],
    cons: ["Expensive", "Parking issues", "Thin walls"],
    reviewer: users[1],
    rent: 1100,
    createdAt: "2025-05-10",
  },
  {
    id: "review-apt-2",
    apartmentName: "NorthView",
    location: "University Blvd",
    rating: 3.8,
    review:
      "Solid student housing. Shuttle is reliable. Rooms are a bit small.",
    pros: ["Shuttle to campus", "Social atmosphere", "Study rooms"],
    cons: ["Small rooms", "Noise on weekends", "Older appliances"],
    reviewer: users[3],
    rent: 750,
    createdAt: "2025-04-22",
  },
  {
    id: "review-apt-3",
    apartmentName: "The Point at Central",
    location: "Central Florida Blvd",
    rating: 4.5,
    review:
      "Best value near campus. Pet friendly and the staff actually cares.",
    pros: ["Affordable", "Pet friendly", "Good maintenance"],
    cons: ["Farther from main campus", "Older building"],
    reviewer: users[4],
    rent: 850,
    createdAt: "2025-03-15",
  },
];

export const tutors: Tutor[] = [
  {
    id: "tutor-1",
    user: users[2],
    subjects: ["Calculus", "Physics", "Engineering"],
    hourlyRate: 25,
    rating: 4.9,
    reviewCount: 34,
    availability: ["Mon 2-6pm", "Wed 3-7pm", "Sat 10am-2pm"],
    bio: "ME sophomore with 2 years tutoring experience. Patient and thorough.",
    sessionsCompleted: 120,
  },
  {
    id: "tutor-2",
    user: users[3],
    subjects: ["Chemistry", "Biology", "Statistics"],
    hourlyRate: 20,
    rating: 4.7,
    reviewCount: 18,
    availability: ["Tue 1-5pm", "Thu 4-8pm", "Sun 12-4pm"],
    bio: "Pre-med track. Love breaking down complex topics into simple steps.",
    sessionsCompleted: 65,
  },
  {
    id: "tutor-3",
    user: users[0],
    subjects: ["Computer Science", "Calculus", "Writing"],
    hourlyRate: 30,
    rating: 4.8,
    reviewCount: 22,
    availability: ["Mon 5-9pm", "Fri 2-6pm"],
    bio: "CS junior. Can help with coding projects, algorithms, and calc.",
    sessionsCompleted: 89,
  },
  {
    id: "tutor-4",
    user: users[4],
    subjects: ["Economics", "Accounting", "Spanish"],
    hourlyRate: 22,
    rating: 4.6,
    reviewCount: 11,
    availability: ["Wed 10am-2pm", "Sat 1-5pm"],
    bio: "Business major, bilingual. Great for intro business courses.",
    sessionsCompleted: 40,
  },
];

export const campusJobs: CampusJob[] = [
  {
    id: "job-1",
    title: "Campus Tour Guide",
    company: "UCF Admissions",
    type: "campus-gig",
    pay: "$15/hr",
    location: "Student Union",
    timeCommitment: "10 hrs/week",
    description:
      "Lead campus tours for prospective students. Flexible scheduling around classes.",
    postedBy: users[1],
    postedAt: "2025-06-20",
    tags: ["On Campus", "Flexible", "Public Speaking"],
  },
  {
    id: "job-2",
    title: "Barista — Campus Coffee Shop",
    company: "Knight Brew Co.",
    type: "part-time",
    pay: "$14/hr + tips",
    location: "Knights Plaza",
    timeCommitment: "15-20 hrs/week",
    description: "Morning and afternoon shifts available. No experience needed.",
    postedBy: users[2],
    postedAt: "2025-06-18",
    tags: ["Food Service", "Tips", "Near Campus"],
  },
  {
    id: "job-3",
    title: "Research Assistant — AI Lab",
    company: "CS Department",
    type: "research",
    pay: "$18/hr",
    location: "HPA II",
    timeCommitment: "12 hrs/week",
    description:
      "Assist with NLP research project. Python experience required.",
    postedBy: users[3],
    postedAt: "2025-06-15",
    tags: ["Research", "CS", "Resume Builder"],
  },
  {
    id: "job-4",
    title: "Event Photographer",
    company: "Knight Life Media",
    type: "freelance",
    pay: "$50/event",
    location: "Various",
    timeCommitment: "Per event",
    description:
      "Cover campus events, club meetings, and sports games. Portfolio required.",
    postedBy: users[4],
    postedAt: "2025-06-22",
    tags: ["Creative", "Photography", "Flexible"],
  },
  {
    id: "job-5",
    title: "Library Student Assistant",
    company: "John C. Hitt Library",
    type: "campus-gig",
    pay: "$13/hr",
    location: "Main Library",
    timeCommitment: "8-12 hrs/week",
    description: "Help with shelving, checkout desk, and study room management.",
    postedBy: users[1],
    postedAt: "2025-06-10",
    tags: ["On Campus", "Quiet", "Study Friendly"],
  },
  {
    id: "job-6",
    title: "Social Media Intern",
    company: "Local Startup",
    type: "freelance",
    pay: "$20/hr",
    location: "Remote / Downtown Orlando",
    timeCommitment: "10 hrs/week",
    description:
      "Manage Instagram and TikTok for a student-founded startup.",
    postedBy: users[4],
    postedAt: "2025-06-25",
    tags: ["Remote", "Marketing", "Startup"],
  },
];

export const campusEvents: CampusEvent[] = [
  {
    id: "event-1",
    title: "Knight Hacks 2025",
    description:
      "48-hour hackathon with $5K in prizes. All skill levels welcome.",
    type: "hackathon",
    date: "2025-09-20",
    time: "9:00 AM",
    location: "Engineering II Atrium",
    host: "Knight Hacks",
    attendeeCount: 156,
    maxAttendees: 200,
    image: "",
  },
  {
    id: "event-2",
    title: "Fall Career Fair",
    description:
      "100+ employers hiring interns and new grads. Business casual required.",
    type: "career-fair",
    date: "2025-09-25",
    time: "10:00 AM",
    location: "CFE Arena",
    host: "Career Services",
    attendeeCount: 890,
    image: "",
  },
  {
    id: "event-3",
    title: "SGA Movie Night — Outdoor Screening",
    description: "Free popcorn, blankets, and a classic movie under the stars.",
    type: "social",
    date: "2025-07-12",
    time: "8:00 PM",
    location: "Memory Mall",
    host: "Student Government",
    attendeeCount: 234,
    image: "",
  },
  {
    id: "event-4",
    title: "Knights vs Cincinnati — Watch Party",
    description: "Cheer on the Knights with free pizza and giveaways.",
    type: "sports",
    date: "2025-10-04",
    time: "7:00 PM",
    location: "Student Union",
    host: "Athletics Dept",
    attendeeCount: 412,
    image: "",
  },
  {
    id: "event-5",
    title: "Pre-Med Society Guest Speaker",
    description: "Dr. Martinez on med school applications and MCAT prep.",
    type: "club",
    date: "2025-07-18",
    time: "6:00 PM",
    location: "HPA I Room 112",
    host: "Pre-Med Society",
    attendeeCount: 67,
    maxAttendees: 80,
    image: "",
  },
  {
    id: "event-6",
    title: "Startup Pitch Night",
    description: "Student founders pitch to local investors. Free entry.",
    type: "club",
    date: "2025-08-05",
    time: "5:30 PM",
    location: "Business Building Atrium",
    host: "Blackstone LaunchPad",
    attendeeCount: 98,
    image: "",
  },
];

export const aiStudyTools: AIStudyTool[] = [
  {
    id: "ai-1",
    name: "Lecture Summarizer",
    description: "Upload lecture notes or slides and get concise summaries.",
    icon: "FileText",
    premium: false,
    usageCount: 1240,
  },
  {
    id: "ai-2",
    name: "Flashcard Generator",
    description: "Turn any text into study flashcards instantly.",
    icon: "Layers",
    premium: false,
    usageCount: 2890,
  },
  {
    id: "ai-3",
    name: "Math Explainer",
    description: "Step-by-step solutions for calc, stats, and linear algebra.",
    icon: "Calculator",
    premium: true,
    usageCount: 1560,
  },
  {
    id: "ai-4",
    name: "Interview Prep",
    description: "Practice behavioral and technical interview questions.",
    icon: "MessageSquare",
    premium: true,
    usageCount: 780,
  },
  {
    id: "ai-5",
    name: "Resume Helper",
    description: "Optimize your resume for internships and new grad roles.",
    icon: "FileCheck",
    premium: true,
    usageCount: 920,
  },
  {
    id: "ai-6",
    name: "Study Plan Builder",
    description: "Generate a personalized study schedule for your exams.",
    icon: "Calendar",
    premium: false,
    usageCount: 1100,
  },
];

export const lostFoundItems: LostFoundItem[] = [
  {
    id: "lf-1",
    title: "UCF Student ID — Alex M.",
    description: "Found near RWC gym entrance. Will verify identity before return.",
    status: "found",
    category: "id-cards",
    location: "RWC Gym",
    date: "2025-06-26",
    reporter: users[5],
  },
  {
    id: "lf-2",
    title: "Lost AirPods Pro Case",
    description: "White case with a knight sticker. Lost near library.",
    status: "lost",
    category: "electronics",
    location: "John C. Hitt Library",
    date: "2025-06-25",
    reporter: users[0],
  },
  {
    id: "lf-3",
    title: "Found Keys with UCF Lanyard",
    description: "Set of keys on a black and gold lanyard. Turned in to SGA office.",
    status: "found",
    category: "keys",
    location: "Student Union",
    date: "2025-06-24",
    reporter: users[3],
  },
  {
    id: "lf-4",
    title: "Lost Calculus Textbook",
    description: "Stewart 8th edition with name written inside cover.",
    status: "lost",
    category: "books",
    location: "Math & Physics Building",
    date: "2025-06-23",
    reporter: users[2],
  },
  {
    id: "lf-5",
    title: "Found Nike Hoodie — Size M",
    description: "Black hoodie left in the gym locker room.",
    status: "found",
    category: "clothing",
    location: "RWC Gym",
    date: "2025-06-22",
    reporter: users[4],
  },
];

export const studentDiscounts: StudentDiscount[] = [
  {
    id: "disc-1",
    businessName: "Black Rock Coffee",
    description: "15% off any drink with student ID. Valid all semester.",
    discount: "15% off",
    category: "coffee",
    location: "Alafaya Trail",
    verified: true,
  },
  {
    id: "disc-2",
    businessName: "Lazy Moon Pizza",
    description: "Free drink with any large pizza. Show Knight Market profile.",
    discount: "Free drink",
    category: "food",
    location: "University Blvd",
    verified: true,
  },
  {
    id: "disc-3",
    businessName: "Orlando Fitness Zone",
    description: "No enrollment fee + first month 50% off for students.",
    discount: "50% off 1st month",
    category: "gym",
    location: "Alafaya Trail",
    expiresAt: "2025-08-31",
    verified: true,
  },
  {
    id: "disc-4",
    businessName: "Campus Copy Center",
    description: "20% off printing and binding. Use code KNIGHT20.",
    discount: "20% off",
    category: "printing",
    location: "Knights Plaza",
    code: "KNIGHT20",
    verified: true,
  },
  {
    id: "disc-5",
    businessName: "iFix Campus Tech",
    description: "$10 off screen repairs for verified students.",
    discount: "$10 off repairs",
    category: "tech-repair",
    location: "University Blvd",
    verified: true,
  },
  {
    id: "disc-6",
    businessName: "Taco Bell — Campus Location",
    description: "Free Baja Blast with any combo meal after 8pm.",
    discount: "Free drink",
    category: "food",
    location: "Knights Plaza",
    verified: false,
  },
];

export const reviews: Review[] = [
  {
    id: "rev-1",
    reviewer: users[2],
    targetId: "user-1",
    targetType: "user",
    rating: 5,
    comment: "Super responsive and the desk was exactly as described!",
    createdAt: "2025-06-15",
  },
  {
    id: "rev-2",
    reviewer: users[3],
    targetId: "user-1",
    targetType: "user",
    rating: 5,
    comment: "Great tutor session — explained calc concepts really clearly.",
    createdAt: "2025-06-10",
  },
  {
    id: "rev-3",
    reviewer: users[1],
    targetId: "listing-2",
    targetType: "listing",
    rating: 4,
    comment: "Book had some extra highlighting but was a fair price.",
    createdAt: "2025-05-28",
  },
];

export const messagePreviews: MessagePreview[] = [
  {
    id: "msg-1",
    participant: users[1],
    lastMessage: "Is the desk still available? I can pick up tomorrow.",
    timestamp: "2025-06-26T14:30:00",
    unread: true,
    context: "IKEA Micke Desk",
    contextType: "listing",
  },
  {
    id: "msg-2",
    participant: users[2],
    lastMessage: "Thanks! See you Wednesday at 3pm for the tutoring session.",
    timestamp: "2025-06-25T18:15:00",
    unread: false,
    context: "Calculus Tutoring",
    contextType: "tutoring",
  },
  {
    id: "msg-3",
    participant: users[3],
    lastMessage: "The room at NorthView is still open if you're interested!",
    timestamp: "2025-06-24T10:00:00",
    unread: true,
    context: "NorthView Sublease",
    contextType: "housing",
  },
  {
    id: "msg-4",
    participant: users[4],
    lastMessage: "Hey! Are you still looking for a roommate?",
    timestamp: "2025-06-23T20:45:00",
    unread: false,
    context: "General",
    contextType: "general",
  },
];

export const myListings = listings.filter((l) => l.sellerId === "seller-5");
